# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  PACKAGE_NAME: teamstest
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: "Install required dependencies"

- script: |
    set -x 
    gulp build
    npm run lint
    npm run ci:test
    gulp manifest
  displayName: 'Build, check code quality, test, and package'

- publish: $(System.DefaultWorkingDirectory)/package
  artifact: $(PACKAGE_NAME).zip


